# Generated by Django 5.0.2 on 2024-03-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=1, upload_to='auth'),
            preserve_default=False,
        ),
    ]
